name: mini_store
description: A.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  sqflite: ^2.2.6
  adaptive_theme: ^3.2.0
  shared_preferences: ^2.1.0
  #crypto: ^3.0.2
  #flutter_secure_storage: ^8.0.0
  introduction_screen: ^3.1.7
  pluto_grid: ^6.0.4
  draggable_home: ^1.0.4
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  image_picker: ^0.8.7+4
  file_picker: ^5.2.10
  qrscan: ^0.3.3
  font_awesome_flutter: ^10.4.0
  permission_handler: ^10.2.0
  currency_picker: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true